/*
# Security Fixes: RLS Policy Hardening

## Security Issues Fixed
1. document_versions INSERT/UPDATE policies were too permissive (WITH CHECK (true))
   - Now only service role can insert/update versions (Edge Functions use service role)
   - Regular authenticated users must use the google-drive-upload Edge Function
2. audit_logs INSERT was too permissive
   - Now only service role can insert audit logs
   - Logs are auto-generated by Edge Functions and triggers
3. document_workflow_events INSERT was too permissive
   - Now only service role can insert workflow events
   - Prevents users from faking approval/rejection events

## Changes Made
- Replace `WITH CHECK (true)` with `TO authenticated` with proper checks
- Use `auth.jwt()` to verify service role for system operations
- Add comment documentation for why policies are restricted

## Non-Goals
- This migration does NOT change data structure
- This migration does NOT delete any data
*/

-- ============================================================================
-- DOCUMENT VERSIONS - Fix overly permissive INSERT/UPDATE policies
-- ============================================================================

-- Drop old policies
DROP POLICY IF EXISTS "Service role can insert versions" ON document_versions;
DROP POLICY IF EXISTS "Service role can update versions" ON document_versions;

-- Only service role (Edge Functions) can insert versions
-- This prevents users from bypassing the google-drive-upload Edge Function
CREATE POLICY "Service role only can insert versions"
ON document_versions FOR INSERT
TO authenticated
WITH CHECK (
    -- Service role has elevated privileges, check via role claim
    (auth.jwt()->>'role' = 'service_role')
);

-- Only service role can update versions (e.g., changing is_current flag)
CREATE POLICY "Service role only can update versions"
ON document_versions FOR UPDATE
TO authenticated
USING (
    (auth.jwt()->>'role' = 'service_role')
)
WITH CHECK (
    (auth.jwt()->>'role' = 'service_role')
);

-- ============================================================================
-- AUDIT LOGS - Prevent fake audit log insertion
-- ============================================================================

DROP POLICY IF EXISTS "Service role can insert audit logs" ON audit_logs;

-- Only service role can insert audit logs
-- This prevents users from creating fake audit trails
CREATE POLICY "Service role only can insert audit logs"
ON audit_logs FOR INSERT
TO authenticated
WITH CHECK (
    (auth.jwt()->>'role' = 'service_role')
);

-- ============================================================================
-- DOCUMENT WORKFLOW EVENTS - Prevent fake approval/rejection
-- ============================================================================

DROP POLICY IF EXISTS "Service role can insert workflow events" ON document_workflow_events;

-- Only service role can insert workflow events
-- This prevents users from faking document approvals/rejections
CREATE POLICY "Service role only can insert workflow events"
ON document_workflow_events FOR INSERT
TO authenticated
WITH CHECK (
    (auth.jwt()->>'role' = 'service_role')
);

-- ============================================================================
-- DOCUMENT PERMISSIONS - Add missing granted_by field enforcement
-- ============================================================================

DROP POLICY IF EXISTS "Users can manage permissions" ON document_permissions;
DROP POLICY IF EXISTS "Users can update permissions" ON document_permissions;
DROP POLICY IF EXISTS "Users can delete permissions" ON document_permissions;

-- Enhanced INSERT policy - granted_by must be the current user
CREATE POLICY "Users can manage permissions"
ON document_permissions FOR INSERT
TO authenticated
WITH CHECK (
    can_manage_document_permissions(document_id)
    AND granted_by = auth.uid()
);

-- Enhanced UPDATE policy
CREATE POLICY "Users can update permissions"
ON document_permissions FOR UPDATE
TO authenticated
USING (can_manage_document_permissions(document_id))
WITH CHECK (can_manage_document_permissions(document_id));

-- Enhanced DELETE policy
CREATE POLICY "Users can delete permissions"
ON document_permissions FOR DELETE
TO authenticated
USING (can_manage_document_permissions(document_id));

-- ============================================================================
-- PROFILES - Prevent role escalation via INSERT
-- ============================================================================

-- The handle_new_user trigger handles new user creation with default role
-- Admin can create profiles manually, but must set role=user by default
DROP POLICY IF EXISTS "Admin can insert profiles" ON profiles;

CREATE POLICY "Admin can insert profiles"
ON profiles FOR INSERT
TO authenticated
WITH CHECK (
    is_admin()
    AND (role = 'user' OR role = 'admin')  -- Can only set valid roles
);
